# Base configs
baseurl: "https://AmartyaCSB.github.io/photography"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-161740824-1"

# UI configs
title: "Photography by Amartya"
subtitle: "Coder who clicks"
author: "Amartya"
header:
 title: "Photography"
 subtitle: "by Amartya"
footer:
 name: "Hey there! I am Amartya."
 bio: "I am currently studying at Georgia Tech for my master's in Bioinformatics. Being a Photography Enthusiast, I love clicking pictures of anything that interests me! I want to see this world for its astonishing place and help others do the same. Hope you have a wonderful time browsing through the images! I have been using Nikon D5100 for a long time."

web_design: "Times of Quarantine"
social_urls:
  facebook: "https://www.facebook.com/amartya7"
  instagram: "https://www.instagram.com/amartya.mandal"
  linkedin: "https://in.linkedin.com/in/mandalamartya"
  github: "https://www.github.com/AmartyaCSB"
